set-option -g prefix m-m
unbind C-b

bind m-m send-prefix 
bind c new-window -c "#{pane_current_path}"

bind s split-window -c "#{pane_current_path}"

bind w split-window -h -c "#{pane_current_path}"

unbind x
bind x kill-pane

# set -ga terminal-overrides ",*256col*:Tc"
# set -ga terminal-overrides ",xterm-256color:Tc"
set -as terminal-overrides ',*:Tc'
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
# underscore colours - needs tmux-3.0
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set-option -g base-index 1
set-option -g pane-base-index 1

set-option -g mouse on

set-option -g set-titles on 
set-option -g set-titles-string "#{base-title}"

set-option -s extended-keys on

larrow="#(printf '\ue0b4')"
rarrow="#(printf '\ue0b6')"

FG="#ebdbb2"
BG="#14161B"

set-option -g status-style bg=${BG},fg=${FG}

set -g status-left-length 100
set -g status-right-length 100

set-option -g status-justify absolute-centre

set-option -g status-left "[#S]"      
set-option -g status-right "Nguyễn Duy Mạnh"

set -g window-status-format "\
 \
#I\
:\
#W\
 \
"
set -g window-status-current-format "\
#[fg=default,bg=default]${rarrow}\
#[fg=${BG},bg=#{FG}]#I:\
#W\
#[fg=default,bg=default]${larrow}\
"

set -g window-status-separator ""

set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set-option -g renumber-windows on

set -g status-position top

set -g pane-border-style fg=#2b2d31
set -g pane-active-border-style fg=#2b2d31

set -ga terminal-overrides ',*:allow-passthrough'
set -ga terminal-overrides ',xtermghostty:allow-passthrough'

# Switch panes using Alt-arrow without prefix

bind -n M-h select-pane -L
bind -n M-l select-pane -R
# bind -n M-k select-pane -U
# bind -n M-j select-pane -D

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-8 select-window -t 8
bind -n M-7 select-window -t 7
bind -n M-9 select-window -t 9

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection 
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel 
unbind -T copy-mode-vi MouseDragEnd1Pane

bind g popup -d "#{pane_current_path}" -E zsh
bind a popup -E python -q
bind M-n popup -h 20% -E 'printf "Window name: "; read name; tmux new-window -n "$name"'
bind f popup -E 'tmux list-windows -F "#{window_index}: #{window_name}" | fzf --layout=reverse | cut -d: -f1 | xargs tmux select-window -t'

bind -n M-s copy-mode
# bind -n M-[ next-window
# bind -n M-] previous-window

run '~/.tmux/plugins/tpm/tpm'

